# Generated by Django 6.0.5 on 2026-07-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='target_audience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
